### ISSUE TITLE
Adding location based information

### ISSUE THREAD

**Issue by jonathanstoker** [irazasyed/laravel-gamp#20]
Is there a way to push geo data like lat / long with a pageview ?

**Comment by irazasyed** [comment]
I don't think there are any specifically supported params for that but if you pass the IP address, then Google will automatically handle that for you.

The closest to your query is [geoid](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#geoid) I could find.

You can explore the docs to see if there are any relevant params for your use case and accordingly use them with the package because all of them are supported.

Hope that helps!
